Weapons/Bolbat/Mines
enemylinegame/SpaceRogue pull request #106
Opened 2023-07-06 15:58 UTC by Bharmaglot

mine factory draft and mine draft

2023-07-18 08:49 UTC, VascoDaKrava requested changes
Необходимо оформить по конвенции. И внести остальные правки

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Enums/EntityType.cs
> +        EnemyAssistant = 6,
6 - не степень двойки.
Смысл флагов - битовое смещение и соответствующая проверка.
Можно, чтобы не путаться, записывать так:
`
None = 0,
Player = 1 << 0,
Enemy = 1 << 1,
EnemyAssistant = 1 << 2,
`
Или бинарно - https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/builtin-types/enum

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
Не по конвенции

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +
Не хватает пустой строки

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +namespace Gameplay.Shooting
Gameplay --> SpaceRogue

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +    public class Mine : IDisposable
sealed?

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +namespace Gameplay.Shooting
Gameplay --> SpaceRogue

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +
Не хватает пустой строки

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +    public class Mine : IDisposable
sealed?

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +        private readonly Updater _updater;
Не обёрнуто в регионы

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +        private readonly Updater _updater;
Не обёрнуто в регионы

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +        private readonly Timer _timerToActivateAlarmSystem;
Всё, что readonly стоит располагать рядом. Удобнее читать

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +        private readonly Updater _updater;
Не обёрнуто в регионы

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +        private readonly Timer _timerToActivateAlarmSystem;
Всё, что readonly стоит располагать рядом. Удобнее читать

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mine.cs
> +        internal Mine(Updater updater, MineView mineView, TimerFactory timerFactory, MineConfig mineConfig)
Зачем интернал? ПОчему не паблик?

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineAlertZoneView.cs
Не по конвенции

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineExploseView.cs
> +    private void CollisionEnter(GameObject go)
Сокращения недопустимы.
Тут точно нужен весь целый геймобджект? Может, сразу требовать IDamageableView ?

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineExploseView.cs
> +        if (damageable is not null)
Геймобджект не нужно проверять на нулл

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineExploseView.cs
> +        if (damageable is not null)
Геймобджект не нужно проверять на нулл

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineView.cs
> +        [SerializeField] internal Transform MineBodyTransform;
Любой другой класс сможет изменить это поле. Так и должно быть?

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/WeaponType.cs
>          Blaster,
enum без нумерации недопустим!

2023-07-18 08:49 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineAlertZoneView.cs
> +    public event Action<EntityViewBase> TargetEnterAlarmZone = (_) => { };
?

2023-07-20 09:42 UTC, Bharmaglot commented on Assets/Scripts/Gameplay/Shooting/Mines/MineExploseView.cs
> +        if (damageable is not null)
Но проверяется - успешно ли получен компонент, а не геймобжект.

2023-07-24 15:06 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineExploseView.cs
> +        if (damageable is not null)
Тогда лучше TryGetComponent для такого случая.
С проверкой на null могут быть различные неприятности.

2023-07-25 20:16 UTC, VascoDaKrava approved these changes
Незначительные замечания по оформлению

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Installers/WeaponsInstaller.cs
Тут две пустые строки надо

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Installers/WeaponsInstaller.cs
>  {
Пространство имён не исправлено

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Installers/WeaponsInstaller.cs
> +
Это не поля - это свойства. Properties

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineAlertZoneView.cs
> +
Строка +1

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineConfig.cs
> +        [field: SerializeField] public MineView Prefab { get; private set; }
Prefab - плохое название. Малоинформативное. Лучше такого именования избегать.
MinePrefab хотя бы.

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineFactory.cs
> +namespace Gameplay.Shooting.Factories
-

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineFactory.cs
> +    public class MineFactory : PlaceholderFactory<Vector2, MineConfig, Mine>
sealed?

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineView.cs
> +    public class MineView : MonoBehaviour
sealed?

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineView.cs
> +        #region Fields
Properties

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MineViewFactory.cs
> +    public class MineViewFactory : PlaceholderFactory<Vector2, MineConfig, MineView>
sealed?

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/Mortar.cs
> +    public class Mortar : Weapon
sealed?

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MortarConfig.cs
> +    public class MortarConfig : WeaponConfig
-

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MortarConfig.cs
> +namespace Gameplay.Shooting.Scriptables
-

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/Mines/MortarConfig.cs
> +
+

2023-07-25 20:16 UTC, VascoDaKrava commented on Assets/Scripts/Gameplay/Shooting/WeaponType.cs
namespace

2023-07-26 19:42 UTC, VascoDaKrava approved these changes

2023-07-26 19:43 UTC, merged